default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_rails_development

test:
  <<: *default
  database: backend_rails_test

production:
  <<: *default
  database: backend_rails_production
  username: backend_rails
  password: <%= ENV['BACKEND_RAILS_DATABASE_PASSWORD'] %>
